# Generated by Django 6.0.3 on 2026-03-10 13:24

import django.db.models.deletion
import laundry_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesananUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('_biaya_tambahan', models.FloatField(default=0.0)),
            ],
            bases=(models.Model, laundry_app.models.KalkulasiLayanan),
        ),
        migrations.CreateModel(
            name='CuciKiloan',
            fields=[
                ('pesananutama_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laundry_app.pesananutama')),
                ('berat_kg', models.FloatField()),
                ('harga_per_kg', models.FloatField(default=8000.0)),
            ],
            bases=('laundry_app.pesananutama',),
        ),
        migrations.CreateModel(
            name='CuciSatuan',
            fields=[
                ('pesananutama_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laundry_app.pesananutama')),
                ('nama_barang', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('harga_per_item', models.FloatField(default=15000.0)),
            ],
            bases=('laundry_app.pesananutama',),
        ),
    ]
