# Generated by Django 6.0.3 on 2026-03-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesananutama',
            name='alamat',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='pesananutama',
            name='no_hp',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='pesananutama',
            name='status_cucian',
            field=models.CharField(default='Proses', max_length=20),
        ),
        migrations.AddField(
            model_name='pesananutama',
            name='status_pembayaran',
            field=models.CharField(default='Belum Lunas', max_length=20),
        ),
    ]
